export const itemsPemohon = [{
  "nama": "Winnah",
  "dari-lembaga": "Anselm",
  "nip": 640522962211257489,
  "golongan": "Ellie",
  "jabatan": "Bogart",
  "status-spd": "ppm",
  "alasan-ditolak": "Donec ut dolor.",
  "no-spd": "109280983",
  "bukti-spd":"tidak ada",
  "status-berkas":"ada"
}, {
  "nama": "Derrick",
  "dari-lembaga": "Elvina",
  "nip": 224570350967765624,
  "golongan": "Pat",
  "jabatan": "Nertie",
  "status-spd": "ovp",
  "alasan-ditolak": "In blandit ultrices enim.",
  "no-spd": "109280983",
  "bukti-spd":"ada",
  "status-berkas":"ada"
}, {
  "nama": "Trish",
  "dari-lembaga": "Dom",
  "nip": 185536539374280496,
  "golongan": "Freddie",
  "jabatan": "Janaye",
  "status-spd": "nco",
  "alasan-ditolak": "In tempor, turpis nec euismod scelerisque.",
  "no-spd": "109280983",
  "bukti-spd":"ada",
  "status-berkas":"ada"
}, {
  "nama": "Reinaldos",
  "dari-lembaga": "Idaline",
  "nip": 891544399443324486,
  "golongan": "Shep",
  "jabatan": "Francyne",
  "status-spd": "qhf",
  "alasan-ditolak": "Fusce posuere felis sed lacus.",
  "no-spd": "109280983",
  "bukti-spd":"ada",
  "status-berkas":"tidak ada"
}, {
  "nama": "Effie",
  "dari-lembaga": "Maxie",
  "nip": 618036849271415324,
  "golongan": "Zachary",
  "jabatan": "Marcelia",
  "status-spd": "alo",
  "alasan-ditolak": "Morbi vel lectus in quam fringilla rhoncus.",
  "no-spd": "109280983",
  "bukti-spd":"tidak ada",
  "status-berkas":"ada"
}, {
  "nama": "Brenda",
  "dari-lembaga": "Brenden",
  "nip": 608915521998035324,
  "golongan": "Jennilee",
  "jabatan": "Spenser",
  "status-spd": "frw",
  "alasan-ditolak": "Proin eu mi.",
  "no-spd": "109280983",
  "bukti-spd":"ada",
  "status-berkas":"ada"
}, {
  "nama": "Mitch",
  "dari-lembaga": "Wainwright",
  "nip": 688827090596375198,
  "golongan": "Reinhold",
  "jabatan": "Janeva",
  "status-spd": "ktw",
  "alasan-ditolak": "In sagittis dui vel nisl.",
  "no-spd": "109280983",
  "bukti-spd":"ada",
  "status-berkas":"ada"
}]

export const itemsEstimasi = [{
  "tanggal-berangkat": "12/30/2020",
  "nama-pemohon": "Alta",
  "dari-lembaga": "Skiba",
  "jenis-pmk": "Audrye",
  "asal": "Nepal",
  "tujuan": "Philippines",
  "banyak": 43,
  "biaya-satuan": 1,
  "total": "74652401.79",
  "status": "thasyts"
}, {
  "tanggal-berangkat": "12/22/2020",
  "nama-pemohon": "Ines",
  "dari-lembaga": "Realpoint",
  "jenis-pmk": "Neile",
  "asal": "Brazil",
  "tujuan": "Uganda",
  "banyak": 24,
  "biaya-satuan": 17,
  "total": "42717826.49",
  "status": "ivbveno"
}, {
  "tanggal-berangkat": "02/25/2020",
  "nama-pemohon": "Brien",
  "dari-lembaga": "Skinix",
  "jenis-pmk": "Lucie",
  "asal": "Indonesia",
  "tujuan": "China",
  "banyak": 74,
  "biaya-satuan": 66,
  "total": "27809696.05",
  "status": "tjqddwy"
}, {
  "tanggal-berangkat": "04/30/2020",
  "nama-pemohon": "Mirilla",
  "dari-lembaga": "Tagopia",
  "jenis-pmk": "Cathlene",
  "asal": "Malaysia",
  "tujuan": "Argentina",
  "banyak": 44,
  "biaya-satuan": 76,
  "total": "82097313.10",
  "status": "fseocka"
}, {
  "tanggal-berangkat": "02/14/2020",
  "nama-pemohon": "Worthy",
  "dari-lembaga": "Jatri",
  "jenis-pmk": "Randy",
  "asal": "Dominican Republic",
  "tujuan": "China",
  "banyak": 27,
  "biaya-satuan": 88,
  "total": "99650380.40",
  "status": "yynywsg"
}, {
  "tanggal-berangkat": "09/22/2020",
  "nama-pemohon": "Eugenius",
  "dari-lembaga": "Gabspot",
  "jenis-pmk": "Florence",
  "asal": "Ukraine",
  "tujuan": "Russia",
  "banyak": 73,
  "biaya-satuan": 57,
  "total": "67290016.73",
  "status": "fghwipw"
}, {
  "tanggal-berangkat": "01/30/2020",
  "nama-pemohon": "Liam",
  "dari-lembaga": "Livetube",
  "jenis-pmk": "Elfrieda",
  "asal": "Sierra Leone",
  "tujuan": "China",
  "banyak": 96,
  "biaya-satuan": 1,
  "total": "75601881.56",
  "status": "hepwscs"
}]

export const itemsPerbandingan = [{
  "tanggal-berangkat": "12/30/2020",
  "nama-pemohon": "Alta",
  "dari-lembaga": "Skiba",
  "jenis-pmk": "Audrye",
  "asal": "Nepal",
  "tujuan": "Philippines",
  "banyak": 43,
  "biaya-satuan": 1,
  "total": "74652401.79",
  "status": "thasyts",
  "maksud-perjalanan-dinas":"lorem ipsum"
}, {
  "tanggal-berangkat": "12/22/2020",
  "nama-pemohon": "Ines",
  "dari-lembaga": "Realpoint",
  "jenis-pmk": "Neile",
  "asal": "Brazil",
  "tujuan": "Uganda",
  "banyak": 24,
  "biaya-satuan": 17,
  "total": "42717826.49",
  "status": "ivbveno",
  "maksud-perjalanan-dinas":"lorem ipsum"
}, {
  "tanggal-berangkat": "02/25/2020",
  "nama-pemohon": "Brien",
  "dari-lembaga": "Skinix",
  "jenis-pmk": "Lucie",
  "asal": "Indonesia",
  "tujuan": "China",
  "banyak": 74,
  "biaya-satuan": 66,
  "total": "27809696.05",
  "status": "tjqddwy",
  "maksud-perjalanan-dinas":"lorem ipsum"
}, {
  "tanggal-berangkat": "04/30/2020",
  "nama-pemohon": "Mirilla",
  "dari-lembaga": "Tagopia",
  "jenis-pmk": "Cathlene",
  "asal": "Malaysia",
  "tujuan": "Argentina",
  "banyak": 44,
  "biaya-satuan": 76,
  "total": "82097313.10",
  "status": "fseocka",
  "maksud-perjalanan-dinas":"lorem ipsum"
}, {
  "tanggal-berangkat": "02/14/2020",
  "nama-pemohon": "Worthy",
  "dari-lembaga": "Jatri",
  "jenis-pmk": "Randy",
  "asal": "Dominican Republic",
  "tujuan": "China",
  "banyak": 27,
  "biaya-satuan": 88,
  "total": "99650380.40",
  "status": "yynywsg",
  "maksud-perjalanan-dinas":"lorem ipsum"
}, {
  "tanggal-berangkat": "09/22/2020",
  "nama-pemohon": "Eugenius",
  "dari-lembaga": "Gabspot",
  "jenis-pmk": "Florence",
  "asal": "Ukraine",
  "tujuan": "Russia",
  "banyak": 73,
  "biaya-satuan": 57,
  "total": "67290016.73",
  "status": "fghwipw",
  "maksud-perjalanan-dinas":"lorem ipsum"
}, {
  "tanggal-berangkat": "01/30/2020",
  "nama-pemohon": "Liam",
  "dari-lembaga": "Livetube",
  "jenis-pmk": "Elfrieda",
  "asal": "Sierra Leone",
  "tujuan": "China",
  "banyak": 96,
  "biaya-satuan": 1,
  "total": "75601881.56",
  "status": "hepwscs",
  "maksud-perjalanan-dinas":"lorem ipsum"
}]

export const itemsBiayaRiil = [{
  "tanggal-berangkat": "12/30/2020",
  "nama-pemohon": "Alta",
  "dari-lembaga": "Skiba",
  "jenis-pmk": "Audrye",
  "asal": "Nepal",
  "tujuan": "Philippines",
  "banyak": 43,
  "biaya-satuan": 1,
  "total": "74652401.79",
  "status": "thasyts",
  "kategori-pmk":"lorem ipsum"
}, {
  "tanggal-berangkat": "12/22/2020",
  "nama-pemohon": "Ines",
  "dari-lembaga": "Realpoint",
  "jenis-pmk": "Neile",
  "asal": "Brazil",
  "tujuan": "Uganda",
  "banyak": 24,
  "biaya-satuan": 17,
  "total": "42717826.49",
  "status": "ivbveno",
  "kategori-pmk":"lorem ipsum"
}, {
  "tanggal-berangkat": "02/25/2020",
  "nama-pemohon": "Brien",
  "dari-lembaga": "Skinix",
  "jenis-pmk": "Lucie",
  "asal": "Indonesia",
  "tujuan": "China",
  "banyak": 74,
  "biaya-satuan": 66,
  "total": "27809696.05",
  "status": "tjqddwy",
  "kategori-pmk":"lorem ipsum"
}, {
  "tanggal-berangkat": "04/30/2020",
  "nama-pemohon": "Mirilla",
  "dari-lembaga": "Tagopia",
  "jenis-pmk": "Cathlene",
  "asal": "Malaysia",
  "tujuan": "Argentina",
  "banyak": 44,
  "biaya-satuan": 76,
  "total": "82097313.10",
  "status": "fseocka",
  "kategori-pmk":"lorem ipsum"
}]